[book]
authors = ["Haoran"]
language = "zh"
multilingual = true
src = "src"
title = "Haoran's webpage"

[build]
build-dir = "docs"
create-missing = false

[output.html.search]
enable = false     # search does not work with chinese
